spring:
  application:
    name: pulgatti-weather

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pulgatti_weather}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  cache:
    type: redis

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${SPRING_KAFKA_PROPERTIES_SASL_MECHANISM:}
      sasl.jaas.config: ${SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG:}
    consumer:
      group-id: weather-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.vinicius.dev.pulgattiwather.history.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  jwt:
    secret: ${APP_JWT_SECRET:/0r0MEgSbOh6oud4Y3vYNB41QZq5fOtOmdjric9molCO58M8QGzo0k/whdUApLXi3ewy+aKGIdua4dUopiKTiQ==}
    expiration-minutes: 60
  open-meteo:
    geocoding-base-url: https://geocoding-api.open-meteo.com/v1
    forecast-base-url: https://api.open-meteo.com/v1
  kafka:
    search-history-topic: search-history-events
  cache:
    weather-forecast-ttl-hours: 24