version: '3.8'

services:
  # --- BANCO DE DADOS (POSTGRESQL) ---
  postgres:
    image: postgres:15-alpine
    container_name: clima-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pulgatti_weather
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clima-network

  # --- CACHE (REDIS) ---
  redis:
    image: redis:7-alpine
    container_name: clima-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - clima-network

  # --- MENSAGERIA (APACHE KAFKA EM MODO KRAFT) ---
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: clima-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REREPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # ID único do Cluster gerado para validação do KRaft
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - clima-network

# Volumes para garantir que seus dados não sumam quando você desligar os containers
volumes:
  postgres_data:
  redis_data:

# Rede interna para permitir que os containers conversem entre si se necessário
networks:
  clima-network:
    driver: bridge